name = "TutorialZH"
uuid = "4d0b14d6-8fbb-11e8-1bfb-818095dff5f7"
authors = ["Roger-luo <hiroger@qq.com>"]
version = "0.1.0"

[deps]
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
